#
# Labtainer Dockerfile
#
#  This is the default Labtainer Dockerfile template, plesae choose the appropriate
#  base image below.
#
# The labtainer.base image includes the following packages:
#    build-essential  expect  file  gcc-multilib  gdb  iputils-ping  less  man  manpages-dev 
#    net-tools  openssh-client  python  sudo  tcl8.6  vim  zip  hexedit  rsyslog
#
# The labtainer.network image adds the following packages:
#   openssl openssh-server openvpn wget tcpdump  update-inetd  xinetd
#
ARG registry
FROM $registry/labtainer.base2
#FROM $registry/labtainer.network
#FROM $registry/labtainer.centos
#FROM $registry/labtainer.lamp
#
#  lab is the fully qualified image name, e.g., mylab.some_container.student
#  labdir is the name of the lab, e.g., mylab 
#  imagedir is the name of the container
#  user_name is the USER from the start.config, if other than ubuntu,
#            then that user must be added in this dockerfile
#            before the USER command
#
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh

RUN sudo apt-get update -y 

RUN sudo apt-get install wget iptables firefox curl apt-utils openjdk-11-jdk apt-transport-https gpg jq ssh apache2 -y

RUN curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elastic.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

RUN sudo apt-get update -y 

RUN sudo apt-get install elasticsearch kibana logstash -y

# Xóa noi dung cu trong cau hình Logstash
RUN echo "" > /etc/logstash/conf.d/apache.conf

# Thêm cau hình Logstash
RUN echo "input {\n\
  beats {\n\
    port => 5044\n\
  }\n\
}" >> /etc/logstash/conf.d/02-beats-input.conf
RUN echo "output {\n\
  if [@metadata][pipeline] {\n\
	elasticsearch {\n\
  	hosts => [\"localhost:9200\"]\n\
  	manage_template => false\n\
  	index => \"%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}\"\n\
  	pipeline => \"%{[@metadata][pipeline]}\"\n\
	}\n\
  } else {\n\
	elasticsearch {\n\
  	hosts => [\"localhost:9200\"]\n\
  	manage_template => false\n\
  	index => \"%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}\"\n\
	}\n\
  }\n\
}" >> /etc/logstash/conf.d/30-elasticsearch-output.conf


# cau hinh elasticsearch
RUN echo "network.host: 0.0.0.0\n\
discovery.type: single-node\n\
" >> /etc/elasticsearch/elasticsearch.yml


#cau hinh kibana
RUN echo "server.host: 0.0.0.0" >> /etc/kibana/kibana.yml



#
#  put package installation here, e.g.,
#     RUN apt-get update && apt-get install -y --no-install-recommends somepackage
#
#
#
# Install the system files found in the _system directory
#
ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /
#
RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo
# replace above with below for centos/fedora
#RUN usermod $user_name -a -G wheel


#
#  **** Perform all root operations, e.g.,           ****
#  **** "apt-get install" prior to the USER command. ****
#
USER $user_name
ENV HOME /home/$user_name
#
# Install files in the user home directory
#
ADD $labdir/$imagedir/home_tar/home.tar $HOME
# remove after docker fixes problem with empty tars
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME
#
#  The first thing that executes on the container.
#
USER root
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]

